name: Build Docker Image

env:
  DOCKER_HUB_REPO: dockkonstantinakk/ta-devops-exam-demo

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test app runs on python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
    #prepare python related executables and environment
      run: |
        python -m pip install --upgrade pip
        factorial.py

  build:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    needs: [test]
    defaults:
      run:
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t $DOCKER_HUB_REPO:$(date '+%Y-%m-%d')-${GITHUB_SHA:0:8} .

      - name: Push to repository
        run: |
          docker login --username dockonstantinakk --password ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker image push --all-tags $DOCKER_HUB_REPO