name: GRC Cloud deploy image

on: [push]
jobs:
  test:
    name: Authenticate to Google Cloud
    runs-on: ubuntu-latest
    steps:
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    name: Use gcloud CLI
      run: gcloud info