name: GRC Cloud deploy image

on: [push]
jobs:
  test:
    name: Authenticate to Google Cloud
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: Setup Google Cloud
      uses: google-github-actions/setup-gcloud@v0
    - name: setup Google Deploy
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: ${{ env.SERVICE }}
        image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}
        region: ${{ env.REGION }}
        env_vars: NAME="TA-Devops-Demo"
    #- name: test the google cloud suite
    #  run: gcloud info