name: GRC Cloud deploy image

on: [push]
jobs:
  test:
    name: Authenticate to Google Cloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
    #prepare python related executables and environment
      run: |
        python -m pip install --upgrade pip
        python factorial.py
    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    #- name: Setup Google Cloud
    #  uses: google-github-actions/setup-gcloud@v0
    - name: setup Google Deploy
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: telerik-github-actions-2021
        image: gcr.io/${{ env.GCP_PROJECT }}/${{ env.SERVICE }}
        region: ${{ env.REGION }}
        env_vars: NAME="telerik-github-actions-2021"
    #- name: test the google cloud suite
    #  run: gcloud info