name: Snyk Python Code Scan
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
        python-version: 3.9
      - name: Install dependencies
    #prepare python related executables and environment
        run: |
        python -m pip install --upgrade pip
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
         args: --package-manager=pip --file=factorial.py